services:
  app:
    # Build configuration
    build:
      context: .
      dockerfile: Dockerfile

    # Container name (optional)
    container_name: pki-microservice

    # Port mapping
    ports:
      - "8080:8080"

    # Volume mounts
    volumes:
      - seed-data:/data
      - cron-output:/cron

      # Key files (local development only)
      - ./student_private.pem:/app/student_private.pem:ro
      - ./student_public.pem:/app/student_public.pem:ro
      - ./instructor_public.pem:/app/instructor_public.pem:ro

    # Environment variables
    environment:
      - TZ=UTC

    # Restart policy
    restart: unless-stopped


volumes:
  seed-data:
  cron-output:
